# Each developer, when first cloning the repository, should
#   copy this file, removing '.example' from its name.
# This file (unless it's -.example.yml) should be listed in .gitignore
#   to keep your settings secret!

# Add account credentials and API keys here.
# See http://railsapps.github.com/rails-environment-variables.html
# Each entry sets a local environment variable and
#   overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
#   makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: Your_Username
GMAIL_PASSWORD: Your_Password
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: please
OMNIAUTH_PROVIDER_KEY: Your_OmniAuth_Provider_Key
OMNIAUTH_PROVIDER_SECRET: Your_OmniAuth_Provider_Secret
ROLES: [admin, user, VIP]
